name: Deploy to Firebase Hosting

on:
  push:
    branches:
      - prod  # Ou votre branche de déploiement

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14' # Spécifiez votre version de Node.js
      - name: Install dependencies
        run: npm install
      - name: Build Angular app
        run: npm run build -- --configuration=production
        env:
          FIREBASE_API_KEY: ${{ secrets.FIREBASE_API_KEY }}
          # Répétez pour les autres variables d'environnement Firebase
      - name: Deploy to Firebase
        uses: w9jds/firebase-action@master
        with:
          args: deploy --only hosting
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
